//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnipiForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int group_id { get; set; }
        public string chat_text { get; set; }
        public System.DateTime chat_time { get; set; }
    }
}
