//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnipiForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.role_users = new HashSet<role_users>();
        }
    
        public int role_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<role_users> role_users { get; set; }
    }
}
