//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnipiForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int id { get; set; }
        public int test_id { get; set; }
        public int diff_id { get; set; }
        public Nullable<int> uli_id { get; set; }
    }
}
